---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7  # really Amazon Linux 2

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    attributes:
